export const laws = [
  {
    id: "265254",
    artikel: "2.11",
    circulair: true,
    titel: "Omgevingswaarden in het omgevingsplan: meer houtbouw, minder CO2",
    kop_1_samenvatting_juridische_maatregel:
      "Wat zijn omgevingswaarden en welk doel hebben ze?  ",
    introductie_juridische_maatregel:
      "Omgevingswaarden zijn instrumenten uit de Omgevingswet die gemeenten kunnen inzetten om beleid uit de gemeentelijke omgevingsvisie uit te voeren. Het doel van omgevingswaarden is om een veilige en gezonde fysieke leefomgeving te creëren. Als de omgevingswaarden in een gebied behaald zijn, zijn activiteiten die de waarde verder verhogen, niet meer toegestaan.",
    kop_2_toepassing_juridische_maatregel:
      "Hoe kan de inzet van omgevingswaarden de circulaire transitie versnellen? ",
    toepassing_juridische_maatregel:
      "Door omgevingswaarden in het omgevingsplan op te nemen, kunnen gemeenten voor bepaalde plangebieden strengere eisen stellen. Een omgevingswaarde kan onder meer bepalen dat in een bepaald gebied niet meer CO2 uitgestoten mag worden. Bosbouw en houtproductie verlagen de hoeveelheid CO2 in de lucht. Zo creëert de omgevingswaarde ruimte voor bosbouw en houtproductie, dat voor houtbouw gebruikt kan worden. ",
    is_er_een_praktijk_voorbeeld: false,
    kop_3_uit_de_praktijk: "Uit de praktijk",
    uit_de_praktijk: "",
    voorbeeld_link: "",
    afbeelding_van_voorbeeld_link: "",
    kop_4_eisen_en_beperkingen: "Omgevingswaarden: eisen en beperkingen",
    eisen_en_beperkingen:
      "- Een omgevingswaarde moet objectief vast te stellen en meetbaar zijn;. \n- Omgevingswaarden zijn alleen zinvol als de activiteit of handeling (bijna) volledig binnen de gemeentegrond valt;\n- Bij elke omgevingswaarde moeten helder de bevoegdheden van het college worden aangegeven. Mag het college bijvoorbeeld op basis van de omgevingswaarde het omgevingsplan wijzigen of omgevingsvergunningen afgeven waarbij van het omgevingsplan afgeweken wordt? De omgevingswaarden moeten duidelijke, bindende kaders verschaffen.\n\n\n",
    kop_5_juridische_toelichting: juridische_toelichting,
    juridische_toelichting:
      "Op grond van artikel 2.11 lid 1 Omgevingswet is de gemeenteraad bevoegd om omgevingswaarden vast te stellen in het omgevingsplan in de zin van artikel 2.4 Omgevingswet.",
    juridische_houdbaarheid: 3,
    duidelijkheid_wet: "",
    beschikbare_jurisprudentie: "",
    complexiteit_maatregel: "",
    kans_op_schadeclaims: "",
    niet_juridische_beoordeling: "",
    juridische_invloed: 2,
    bereik: "",
    duur: "",
    frequentie: "",
    omvang: "",
    nationaal: false,
    provinciaal: false,
    waterschappen: false,
    gemeentelijk: true,
    type_beleidsinstrument: "Juridisch",
    planningsfase_binnen_de_gebiedsontwikkeling: "Verkenning",
    ketenfase_van: "",
    R1: true,
    R2: true,
    R3: false,
    R4: false,
    R5: false,
    R6: false,
    valt_deze_mogelijkheid_onder_een_overheidsopdracht_of_consessie_opdracht: false,
    soort_opdracht: "",
    waar_valt_het_onder: "",
    kop_6_ministappenplan:
      "Deze maatregel is nog niet in werking getreden en nog niet toegepast",
    ministappenplan:
      "In de toekomst vind je hier een interactieve handleiding die je meeneemt in hoe je: \n\n- met de maatregel een project vormt en hiermee met de markt mee aan de slag kan gaan\n\n- intern kunt checken of het haalbaar, realistisch en het goede moment is om de maatregel toe te passen\n\n- de maatregel kan combineren met andere juridische, financiële en faciliterende beleidsinstrumenten, om zo meer impact te maken  ",
    links_ministappenplan: "",
    goed_in_combinatie_met_maatregel_vul_in_titel_voor_meer_mogelijkheden_vul_in_met_komma:
      "",
    rechtsgebied: "Publiekrecht",
    subrechtsgebied: "Omgevingsrecht",
    citeertitel: "Omgevingswet",
    geldend_vanaf: "Nog niet inwerking getreden",
    type_document: "Wet in formele zin",
    waardeketen: {
      transitieagenda: "Gebouwde Omgeving",
    },
    casus: "Houtbouw",
  },
  {
    id: "2",
    artikel: "3.1",
    circulair: true,
    titel: "Houtbouw een plek geven in de gemeentelijke omgevingsvisie ",
    kop_1_samenvatting_juridische_maatregel:
      "Wat staat er in de gemeentelijke omgevingsvisie?",
    introductie_juridische_maatregel:
      "In de gemeentelijke omgevingsvisie beschrijft de gemeente de integrale langetermijnvisie voor de fysieke leefomgeving. De visie geeft aan welke gemeentelijke kernkwaliteiten beschermd moeten worden en wat de maatschappelijke uitdaging is. De omgevingsvisie is de basis van het te vormen omgevingsbeleid en kan onder meer betrekking hebben op:\n- ruimtelijke aspecten;\n- energie-infrastructuur;\n- landbouw;\n- landschap;\n- milieu;\n- natuur;\n- water.\n\n",
    kop_2_toepassing_juridische_maatregel:
      "Hoe kan de gemeentelijke omgevingsvisie houtbouw bevorderen? ",
    toepassing_juridische_maatregel:
      "Door houtbouw in de gemeentelijk omgevingsvisie op te nemen, wordt het onderdeel van de beleidscyclus van de Omgevingswet. Dat maakt het mogelijk om later in de beleidscyclus houtbouw op de agenda te zetten. Vanuit de omgevingsvisie komen andere maatregelen – zoals omgevingsvergunningen, een omgevingsplan of omgevingswaarden – voort. Die kunnen vervolgens ingezet worden om houtbouw te stimuleren of af te dwingen.   ",
    is_er_een_praktijk_voorbeeld: true,
    kop_3_uit_de_praktijk: "Uit de praktijk",
    uit_de_praktijk:
      "De gemeente Amsterdam heeft houtbouw opgenomen in haar omgevingsplan. Op pagina 176  en 203 vind je er meer over terug.",
    voorbeeld_link: "https://amsterdam2050.nl/",
    afbeelding_van_voorbeeld_link: "",
    kop_4_eisen_en_beperkingen:
      "Gemeentelijke omgevingsvisie: eisen en beperkingen",
    eisen_en_beperkingen:
      "De omgevingsvisie is zelfbindend voor het bestuursorgaan dat het heeft opgesteld. De visie geldt dus niet voor burgers, bedrijven of andere overheden. Ook betekent het dat er geen bezwaar en beroep tegen de visie mogelijk is. Wel mag iedereen in de voorbereiding van de omgevingsvisie zienswijzen naar voren brengen.  ",
    kop_5_juridische_toelichting: juridische_toelichting,
    juridische_toelichting:
      "Op grond van artikel 3.1 lid 1 Omgevingswet kan een gemeentelijke omgevingsvisie worden vastgesteld.",
    juridische_houdbaarheid: 5,
    duidelijkheid_wet: "",
    beschikbare_jurisprudentie: "",
    complexiteit_maatregel: "",
    kans_op_schadeclaims: "",
    niet_juridische_beoordeling: "",
    juridische_invloed: 3,
    bereik: "",
    duur: "",
    frequentie: "",
    omvang: "",
    nationaal: false,
    provinciaal: false,
    waterschappen: false,
    gemeentelijk: true,
    type_beleidsinstrument: "Juridisch",
    planningsfase_binnen_de_gebiedsontwikkeling: "Verkenning",
    ketenfase_van: "Gebruik",
    R1: true,
    R2: true,
    R3: false,
    R4: false,
    R5: false,
    R6: false,
    valt_deze_mogelijkheid_onder_een_overheidsopdracht_of_consessie_opdracht: false,
    soort_opdracht: "",
    waar_valt_het_onder: "",
    kop_6_ministappenplan: "Zelf houtbouw een plek geven in de omgevingsvisie?",
    ministappenplan:
      "In de toekomst vind je hier een stappenplan om houtbouw op te nemen in de omgevingsvisie",
    links_ministappenplan: "",
    goed_in_combinatie_met_maatregel_vul_in_titel_voor_meer_mogelijkheden_vul_in_met_komma:
      "",
    rechtsgebied: "Publiekrecht",
    subrechtsgebied: "Omgevingsrecht",
    citeertitel: "Omgevingswet",
    geldend_vanaf: "Nog niet inwerking getreden",
    type_document: "Wet in formele zin",
    waardeketen: {
      transitieagenda: "Gebouwde Omgeving",
    },
    casus: "Houtbouw",
  },
  {
    id: "3",
    artikel: "4.159",
    circulair: true,
    titel: "Hoe een maatwerkregel over de MPG houtbouw kan stimuleren",
    kop_1_samenvatting_juridische_maatregel: "Wat zijn maatwerkregels? ",
    introductie_juridische_maatregel:
      "Maatwerkregels zijn instrumenten waarmee de gemeente aanvullende regels kan stellen. Een algemene regel van het Rijk of de provincie is de basis; de maatwerkregel is een lokale uitwerking of aanscherping ervan. Maatwerkregels kunnen over verschillende onderwerpen gaan, waaronder de MilieuPrestatie Gebouwen (MPG). ",
    kop_2_toepassing_juridische_maatregel:
      "Hoe kan een maatwerkregel over de MPG houtbouw stimuleren? ",
    toepassing_juridische_maatregel:
      "De MPG is een objectieve maatstaf voor de duurzaamheid van een gebouw. Het geeft aan hoe milieubelastend de materialen zijn die in een gebouw zijn gebruikt. Specifiek gaat het om nieuwbouwwoningen en kantoorgebouwen. Hoe duurzamer het gebruikte materiaal, hoe lager de milieuprestatie van het gebouw, des te minder het milieu belast wordt. Dankzij de duurzaamheid van hout leidt houtbouw tot een lage MPG. Door in een bepaald gebied de MPG te verlagen, moedigt de gemeente houtbouw aan. ",
    is_er_een_praktijk_voorbeeld: false,
    kop_3_uit_de_praktijk: "Uit de praktijk",
    uit_de_praktijk: "",
    voorbeeld_link: "",
    afbeelding_van_voorbeeld_link: "",
    kop_4_eisen_en_beperkingen: "Eisen aan en beperkingen van maatwerkregels",
    eisen_en_beperkingen:
      "- Maatwerkregels van de gemeente worden altijd in het omgevingsplan opgenomen;\n- Decentrale bestuursorganen mogen alleen maatwerkregels vaststellen mits zij daarvoor toestemming hebben van een hoger bestuursorgaan;\n- De huidige MPG is wettelijk vastgesteld op 0,8;\n- Een maatwerkregel over de MPG kan alleen worden vastgesteld voor nieuwbouwwoningen of voor kantoorgebouwen groter dan 100 m²;\n- Maatwerkregels moeten altijd een beleidsdoel dienen, zoals het bevorderen van de fysieke leefomgeving of verbeteren van de veiligheid.",
    kop_5_juridische_toelichting: juridische_toelichting,
    juridische_toelichting:
      "Op grond van artikel 4.7 Ow kunnen maatwerkregels worden vastgesteld op o.a. artikel 4.159 Ow.",
    juridische_houdbaarheid: 5,
    duidelijkheid_wet: "",
    beschikbare_jurisprudentie: "",
    complexiteit_maatregel: "",
    kans_op_schadeclaims: "",
    niet_juridische_beoordeling: "",
    juridische_invloed: 3,
    bereik: "",
    duur: "",
    frequentie: "",
    omvang: "",
    nationaal: false,
    provinciaal: false,
    waterschappen: false,
    gemeentelijk: true,
    type_beleidsinstrument: "Juridisch",
    planningsfase_binnen_de_gebiedsontwikkeling: "Verkenning",
    ketenfase_van: "",
    R1: false,
    R2: true,
    R3: false,
    R4: false,
    R5: false,
    R6: false,
    valt_deze_mogelijkheid_onder_een_overheidsopdracht_of_consessie_opdracht: false,
    soort_opdracht: "",
    waar_valt_het_onder: "",
    kop_6_ministappenplan:
      "Deze maatregel is nog niet in werking getreden en nog niet toegepast",
    ministappenplan:
      "In de toekomst vind je hier een interactieve handleiding die je meeneemt in hoe je: \n- met de maatregel een project vormt en hiermee met de markt mee aan de slag kan gaan\n- intern kunt checken of het haalbaar, realistisch en het goede moment is om de maatregel toe te passen\n- de maatregel kan combineren met andere juridische, financiële en faciliterende beleidsinstrumenten, om zo meer impact te maken  ",
    links_ministappenplan:
      "https://iplo.nl/regelgeving/regels-voor-activiteiten/technische-bouwactiviteit/rijksregels-bouwactiviteit/milieuprestatie-bbl/ \n\nhttps://www.metropoolregioamsterdam.nl/wp-content/uploads/2021/10/Convenant-Green-Deal-Houtbouw.pdf\n\n",
    goed_in_combinatie_met_maatregel_vul_in_titel_voor_meer_mogelijkheden_vul_in_met_komma:
      "",
    rechtsgebied: "Publiekrecht",
    subrechtsgebied: "Omgevingsrecht",
    citeertitel: "Omgevingswet",
    geldend_vanaf: "Nog niet inwerking getreden",
    type_document: "AMvB",
    waardeketen: {
      transitieagenda: "Gebouwde Omgeving",
    },
    casus: "Houtbouw",
  },
  {
    id: "4",
    artikel: "9.1",
    circulair: true,
    titel: "Het gemeentelijk voorkeursrecht als aanjager van houtbouw",
    kop_1_samenvatting_juridische_maatregel:
      "Wat is het gemeentelijk voorkeursrecht?",
    introductie_juridische_maatregel:
      "Voorkeursrecht geeft de overheid het eerste recht op de koop van gronden en gebouwen. ",
    kop_2_toepassing_juridische_maatregel:
      "Hoe het gemeentelijk voorkeursrecht houtbouw kan stimuleren",
    toepassing_juridische_maatregel:
      "Op basis van het voorkeursrecht kan de gemeente verouderde gebouwen opkopen. Zo vergroot de gemeente de hoeveelheid nieuwe gemeentegrond en waarborgt ze dat een eventuele verbouwing en/of nieuwbouw circulair aanbesteed wordt. In de aanbesteding kan de gemeente bijvoorbeeld eisen dat er met hout ge- of verbouwd wordt. ",
    is_er_een_praktijk_voorbeeld: false,
    kop_3_uit_de_praktijk: "Uit de praktijk",
    uit_de_praktijk: "",
    voorbeeld_link: "",
    afbeelding_van_voorbeeld_link: "",
    kop_4_eisen_en_beperkingen:
      "Gemeentelijk voorkeursrecht: eisen en beperkingen ",
    eisen_en_beperkingen:
      "- De gemeente kan niet in alle situaties een voorkeursrecht vestigen. De Omgevingswet bepaalt in welke gevallen dit kan; \n- Per locatie kan maar één voorkeursrecht gelden; \n- Het voorkeursrecht kan alleen gevestigd worden op onroerende zaken die deel uitmaken van een niet-agrarische locatie én waarvan het huidige gebruik afwijkt van de toebedeelde functie.",
    kop_5_juridische_toelichting: juridische_toelichting,
    juridische_toelichting:
      "Ingevolge art. 9.1 lid 1 Ow kan de raad bij voorkeursrechtbeschikking op een onroerende zaak een gemeentelijk voorkeursrecht vestigen op basis van de gemeentelijke omgevingsvisie.",
    juridische_houdbaarheid: 3,
    duidelijkheid_wet: "",
    beschikbare_jurisprudentie: "",
    complexiteit_maatregel: "",
    kans_op_schadeclaims: "",
    niet_juridische_beoordeling: "",
    juridische_invloed: 1,
    bereik: "",
    duur: "",
    frequentie: "",
    omvang: "",
    nationaal: false,
    provinciaal: false,
    waterschappen: false,
    gemeentelijk: true,
    type_beleidsinstrument: "Juridisch",
    planningsfase_binnen_de_gebiedsontwikkeling: "Verkenning",
    ketenfase_van: "",
    R1: true,
    R2: true,
    R3: false,
    R4: false,
    R5: false,
    R6: false,
    valt_deze_mogelijkheid_onder_een_overheidsopdracht_of_consessie_opdracht: false,
    soort_opdracht: "",
    waar_valt_het_onder: "",
    kop_6_ministappenplan: "Aan de slag met voorkeursrecht?",
    ministappenplan:
      "In de toekomst vind je hier een stappenplan om als gemeente met  voorkeursrecht houtbouw aan te jagen.",
    links_ministappenplan: "",
    goed_in_combinatie_met_maatregel_vul_in_titel_voor_meer_mogelijkheden_vul_in_met_komma:
      "",
    rechtsgebied: "Publiekrecht",
    subrechtsgebied: "Omgevingsrecht",
    citeertitel: "Omgevingswet",
    geldend_vanaf: "Nog niet inwerking getreden",
    type_document: "Wet in formele zin",
    waardeketen: {
      transitieagenda: "Gebouwde Omgeving",
    },
    casus: "Houtbouw",
  },
  {
    id: "5",
    artikel: "2.75",
    circulair: true,
    titel:
      "Hoe technische specificaties in overheidsopdrachten houtbouw kunnen bevorderen",
    kop_1_samenvatting_juridische_maatregel:
      "Wat zijn technische specificaties en wanneer worden ze gebruikt? ",
    introductie_juridische_maatregel:
      "In aanbestedingsstukken worden regelmatig technische specificaties opgenomen. In deze specificaties staan de eisen waar de opdracht aan moet voldoen. Een inschrijving die niet aan de eisen voldoet, komt sowieso niet in aanmerking. \n\nTechnische specificaties kunnen op twee manieren geformuleerd worden: in technische of functionele eisen. Technische eisen benoemen exact de criteria waar een product, dienst of levering aan moet voldoen. Functionele eisen zijn minder afgekaderd. Die beschrijven slechts in hoofdlijnen waar een product, dienst of levering aan moet voldoen. Dat biedt ruimte voor innovatieve ideeën. \n\nMet technische en functionele eisen kunnen circulaire doelen op het gebied van ontwerp en productiemateriaal (makkelijker) behaald worden. ",
    kop_2_toepassing_juridische_maatregel:
      "Hoe kunnen technische specificaties houtbouw bevorderen?",
    toepassing_juridische_maatregel:
      "Een technische eis kan zijn dat een gebouw een houtskelet moet hebben, of dat bij de bouw gebruik gemaakt moet worden van CLT. Hoe werkt dat in de praktijk? Houtproductie stoot significant minder CO2 uit dan beton. Door houtbouw kan CO2 voor langere tijd in een gebouw en de gebouwde omgeving worden opgeslagen. Daarmee levert houtskeletbouw een wezenlijke bijdrage aan verdere reductie van CO2 en aan de circulaire economie. In sommige gevallen is de hoeveelheid opgeslagen CO2 zelfs groter dan de uitstoot: dan spreken we over een CO2-negatief gebouw. \n\nFunctionele eisen hebben ook een directe relatie tot houtbouw. Stel dat een functionele eis luidt: ‘Het gebouw moet na vijftien jaar verplaatst of afgebroken kunnen worden en zonder hoge milieu-impact op een andere locatie hergebruikt kunnen worden’. Doordat houten gebouwen relatief lichtgewicht en makkelijk te demonteren zijn, voldoen deze gebouwen gemakkelijker aan deze eis.  ",
    is_er_een_praktijk_voorbeeld: false,
    kop_3_uit_de_praktijk: "Uit de praktijk",
    uit_de_praktijk: "",
    voorbeeld_link: "",
    afbeelding_van_voorbeeld_link: "",
    kop_4_eisen_en_beperkingen:
      "Technische specificaties: eisen en beperkingen",
    eisen_en_beperkingen:
      "- Een technische specificatie in de aanbesteding opnemen heeft alleen zin als meerdere bedrijven aan de eis voldoen. Wanneer het gaat om innovatieve oplossingen, kan het aantal partijen in de markt dat die oplossing biedt, beperkt zijn. Dan is het onverstandig en onevenredig om zo’n eis op te nemen. In dat geval is een subgunningscriterium een beter alternatief;  \n- Als de specificatie naar een bepaalde norm verwijst, moet deze gepaard gaan met de woorden ‘of gelijkwaardig’. Als een inschrijver bijvoorbeeld niet beschikt over het specifieke keurmerk waarom gevraagd wordt, maar wel een ander, vergelijkbaar certificaat heeft, kan hij dit in plaats daarvan aanwenden. Zo kunnen ook partijen met een gelijkwaardige oplossing zich inschrijven; \n- Een technische specificatie mag niet verwijzen naar een product, merk, octrooi of type waardoor een bepaald bedrijf bevoordeeld of uitgesloten wordt. Wanneer een opdracht daar specifiek om vraagt, geldt een uitzondering. ",
    kop_5_juridische_toelichting: juridische_toelichting,
    juridische_toelichting:
      "Dit volgt uit art. 2.75 jo. 2.76 Aanbestedingswet.\n\nDe volgende specifieke artikelen uit het Aanbestedingsreglement zien op technische specificaties binnen een bepaalde procedure:\n- Openbare procedure: art. 2.10 Aanbestedingsreglement\n- Niet-openbare procedure: art. 3.10 Aanbestedingsreglement\n- Procedure van de concurrentiegerichte dialoog: art. 4.10 Aanbestedingsreglement\n- Mededingingsprocedure met onderhandeling: art. 5.10 Aanbestedingsreglement\n- Onderhandelingsprocedure zonder aankondiging: art. 6.9 Aanbestedingsreglement\n- Procedure van innovatiepartnerschap: art. 8.10 Aanbestedingsreglement\n\n\n\n",
    juridische_houdbaarheid: 2,
    duidelijkheid_wet: "",
    beschikbare_jurisprudentie: "",
    complexiteit_maatregel: "",
    kans_op_schadeclaims: "",
    niet_juridische_beoordeling: "",
    juridische_invloed: 3,
    bereik: "",
    duur: "",
    frequentie: "",
    omvang: "",
    nationaal: false,
    provinciaal: false,
    waterschappen: false,
    gemeentelijk: true,
    type_beleidsinstrument: "Juridisch",
    planningsfase_binnen_de_gebiedsontwikkeling: "Verkenning",
    ketenfase_van: "",
    R1: true,
    R2: true,
    R3: false,
    R4: false,
    R5: true,
    R6: false,
    valt_deze_mogelijkheid_onder_een_overheidsopdracht_of_consessie_opdracht: true,
    soort_opdracht: "Overheidsopdracht",
    waar_valt_het_onder: "Bestek",
    kop_6_ministappenplan:
      "Zo neem je technische specificaties op in aanbestedingsstukken",
    ministappenplan:
      "1. Neem contact op met inkoop\n\n2. Pak het ‘Handvat functioneel specificeren’ en de ‘Leidraad Circulair Inkopen in de Bouw’ erbij ter inspiratie en nadere uitleg van de eventuele mogelijkheden\n\n3. Bepaal de behoefte van de organisatie en verzamel de benodigde gegevens\n\n4. Stel samen met inkoop de technische specificaties op",
    links_ministappenplan:
      "https://www.pianoo.nl/sites/default/files/documents/documents/ienmhandvatfunctioneelspecificerennl.pdf\n\nhttps://platformcb23.nl/images/consultatie/leidraden/2021/PlatformCB23_Conceptleidraad_Circulair-Inkopen_17032021.pdf",
    goed_in_combinatie_met_maatregel_vul_in_titel_voor_meer_mogelijkheden_vul_in_met_komma:
      "",
    rechtsgebied: "Privaatrecht",
    subrechtsgebied: "Aanbesteding",
    citeertitel: "Aanbestedingswet 2012",
    geldend_vanaf: "18 april 2019",
    type_document: "Wet in formele zin",
    waardeketen: {
      transitieagenda: "Gebouwde Omgeving",
    },
    casus: "Houtbouw",
  },
  {
    id: "6",
    artikel: "2.155a",
    circulair: true,
    titel: "Levenscycluskosten als gunningscriterium, meer houtbouw",
    kop_1_samenvatting_juridische_maatregel: "Wat zijn levenscycluskosten?",
    introductie_juridische_maatregel:
      "Levenscycluskosten zijn alle kosten die verband houden met het onderhoud, verbruik, hergebruik of verwijdering van een product of dienst. Ook kosten gerelateerd aan externe milieueffecten vallen onder de levenscycluskosten. Dat kunnen kosten zijn voor  milieuverontreiniging die wordt veroorzaakt door winning van een bepaalde grondstof, verontreiniging door het product zelf of als gevolg van de productie ervan. Kortom: levenscycluskosten zijn alle kosten van een product waar men vandaag, morgen en in de verre toekomst rekening mee moet houden. Bij de gunning van een opdracht kunnen levenscycluskosten doorslaggevend zijn. In dat geval wint de inschrijving die de laagste levenscycluskosten garandeert. ",
    kop_2_toepassing_juridische_maatregel:
      "Hoe kunnen levenscycluskosten de circulaire transitie versnellen?",
    toepassing_juridische_maatregel:
      "Houtbouwprojecten hebben relatief lage levenscycluskosten. Hout verwerken kost minder energie dan de productie van bijvoorbeeld beton of staal. Ook wordt er tijdens de productie van hout minder CO2 uitgestoten. Bovendien slaat hout langdurig CO2 op, waardoor er meer CO2 uit de lucht gehaald wordt. Kortom: met levenscycluskosten als gunningscriterium bij een aanbesteding hebben houtbouwprojecten een streepje voor.",
    is_er_een_praktijk_voorbeeld: false,
    kop_3_uit_de_praktijk: "Uit de praktijk",
    uit_de_praktijk: "",
    voorbeeld_link: "",
    afbeelding_van_voorbeeld_link: "",
    kop_4_eisen_en_beperkingen: "Levenscycluskosten: eisen en beperkingen",
    eisen_en_beperkingen:
      "De berekeningsmethode van de externe milieueffecten moet voldoen aan drie voorwaarden, zoals vastgesteld in de Aanbestedingswet (art. 2.115a lid 3):\n\n- De methode moet gebaseerd zijn op objectief controleerbare en niet-discriminerende criteria;\n- Alle inschrijvers moeten de berekeningsmethode kunnen inzien;\n- De gevraagde gegevens moeten met een redelijke inspanning door normaal zorgvuldige ondernemers kunnen worden verstrekt. Met andere woorden: het moet de inschrijver niet te veel inspanning kosten om de gevraagde gegevens aan te leveren. \n\nWanneer EU-regelgeving het verplicht een bepaalde berekeningsmethode te gebruiken voor de levenscycluskosten, dan moet die methode worden toegepast. In dat geval mogen geen andere berekeningsmethoden worden gebruikt.  ",
    kop_5_juridische_toelichting: juridische_toelichting,
    juridische_toelichting:
      "Dit volgt uit art. 2.114 lid 2 sub b jo. 2.115a Aanbestedingswet.",
    juridische_houdbaarheid: 3,
    duidelijkheid_wet: "",
    beschikbare_jurisprudentie: "",
    complexiteit_maatregel: "",
    kans_op_schadeclaims: "",
    niet_juridische_beoordeling: "",
    juridische_invloed: 3,
    bereik: "",
    duur: "",
    frequentie: "",
    omvang: "",
    nationaal: false,
    provinciaal: false,
    waterschappen: false,
    gemeentelijk: true,
    type_beleidsinstrument: "Juridisch",
    planningsfase_binnen_de_gebiedsontwikkeling: "Verkenning",
    ketenfase_van: "",
    R1: true,
    R2: false,
    R3: false,
    R4: false,
    R5: false,
    R6: false,
    valt_deze_mogelijkheid_onder_een_overheidsopdracht_of_consessie_opdracht: false,
    soort_opdracht: "",
    waar_valt_het_onder: "",
    kop_6_ministappenplan: "Start met levenscycluskosten als gunningscriterium",
    ministappenplan:
      "1. Maak een afweging of gunnen op basis van levenscycluskosten het beste bij de opdracht past\n\n2. Bij de afweging kun je gebruik maken van de  factsheet: Levenscycluskosten als gunningscriterium 2016\n\n3. Kies je voor gunnen op basis van levenscycluskosten? Dan moet je dit motiveren",
    links_ministappenplan: "",
    goed_in_combinatie_met_maatregel_vul_in_titel_voor_meer_mogelijkheden_vul_in_met_komma:
      "",
    rechtsgebied: "Privaatrecht",
    subrechtsgebied: "Aanbesteding",
    citeertitel: "Aanbestedingswet 2012",
    geldend_vanaf: "18 april 2019",
    type_document: "Wet in formele zin",
    waardeketen: {
      transitieagenda: "Gebouwde Omgeving",
    },
    casus: "Houtbouw",
  },
  {
    id: "7",
    artikel: "5.85",
    circulair: true,
    titel:
      "Erfpacht: duurzaamheidseisen in tenders en samenwerkingsovereenkomsten    ",
    kop_1_samenvatting_juridische_maatregel:
      "Wat houdt het recht op erfpacht in? ",
    introductie_juridische_maatregel:
      "Erfpacht geeft aan onder welke voorwaarden bepaalde grond mag worden gebruikt. In de meeste gevallen gaan erfpachtvoorwaarden over de bestemming van het terrein (woon- of bedrijfsruimte) of over de maximale bebouwing. ",
    kop_2_toepassing_juridische_maatregel:
      "Hoe kan erfpacht de circulaire transitie versnellen? ",
    toepassing_juridische_maatregel:
      "Strikt genomen kunnen gemeenten in erfpachtvoorwaarden geen duurzaamheidseisen stellen. Dat betekent echter niet dat een gemeente per definitie geen duurzaamheidsaspecten in de gronduitgifte op kan nemen. Wanneer er sprake is van ‘gelijkwaardigheid en vrijwilligheid’, kan dat namelijk wél. Deze gelijkwaardigheid en vrijwilligheid kan op twee manieren gerealiseerd worden: door een tender uit te schrijven of door een samenwerkingsovereenkomst te sluiten.  ",
    is_er_een_praktijk_voorbeeld: true,
    kop_3_uit_de_praktijk:
      "* Duurzaamheid als belangrijk(ste) criterium in een tender\n",
    uit_de_praktijk:
      "Inschrijving voor een tender is vrijwillig. De gemeente bepaalt voor elke tender aan welke voorwaarden partijen moeten voldoen en welke criteria prioriteit krijgen. De gemeente kan ervoor kiezen het meeste gewicht toe te kennen aan duurzaamheidseisen. De partij die op duurzaamheidsniveau het beste scoort, wint de tender. Deze partij krijgt vervolgens een optieovereenkomst, waarmee het een jaar lang recht op erfpacht heeft. Uitgangspunt van de overeenkomst is het definitieve ontwerp, dat volledig aan de duurzaamheidseisen voldoet. Op basis van deze overeenkomst kan de gemeente de duurzaamheidseisen handhaven.   \n\n[KADER] Tender in de praktijk (1): Roadmap Circulaire Gronduitgifte\nDe gemeente Amsterdam introduceerde in 2017 de Roadmap Circulaire Gronduitgifte. Daarmee stimuleert, meet en beloont het het circulair bouwen en innoveren in de stad. De gemeente laat zien hoe je dit door een tender kunt bereiken. Lees hier meer over de roadmap en hoe je een circulaire tender kunt vormgeven:\nhttps://www.pianoo.nl/nl/document/14280/roadmap-circulaire-gronduitgifte\n\n[KADER] Tender in de praktijk (2): HAUT\nIn 2016 schreef de gemeente Amsterdam een tender uit voor een gebouw in het Amstelkwartier. Het duurzame ontwerp voor het gebouw ‘HAUT’ was de winnende inschrijving. Met een hoogte van 73 meter en 21 verdiepingen wordt HAUT de hoogste houten woontoren van Nederland. Meer informatie vind je hier: https://hautamsterdam.nl/nl/.\n\n",
    voorbeeld_link:
      "https://www.pianoo.nl/nl/document/14280/roadmap-circulaire-gronduitgifte\n\nhttps://hautamsterdam.nl/nl/",
    afbeelding_van_voorbeeld_link: "",
    kop_4_eisen_en_beperkingen:
      "* Commitment voor duurzaamheid in samenwerkingsovereenkomsten",
    eisen_en_beperkingen:
      "Ook in samenwerkingsovereenkomsten kan sprake zijn van vrijwilligheid en gelijkwaardigheid. Bijvoorbeeld als de overeenkomst tussen de gemeente (als grondeigenaar) en de wederpartij niet uitsluitend over de in erfpacht uit te geven grond gaat. Dit is vaak het geval bij grootschalige nieuwbouwprojecten. Bij zo’n project sluiten gemeenten en professionele marktpartijen samenwerkingscontracten af. Daarin moet een clausule worden opgenomen waaruit blijkt dat alle partijen zich realiseren dat de gestelde eisen verder gaan dan de eisen van het Bouwbesluit. Ook stelt de clausule dat de partijen zich vrijwillig inzetten om een hogere bouwkwaliteit te realiseren. ",
    kop_5_juridische_toelichting: juridische_toelichting,
    juridische_toelichting:
      "Dit volgt uit art. 122 Woningwet en het Bouwbesluit. ",
    juridische_houdbaarheid: 3,
    duidelijkheid_wet: "",
    beschikbare_jurisprudentie: "",
    complexiteit_maatregel: "",
    kans_op_schadeclaims: "",
    niet_juridische_beoordeling: "",
    juridische_invloed: 3,
    bereik: "",
    duur: "",
    frequentie: "",
    omvang: "",
    nationaal: false,
    provinciaal: false,
    waterschappen: false,
    gemeentelijk: true,
    type_beleidsinstrument: "Juridisch",
    planningsfase_binnen_de_gebiedsontwikkeling: "Verkenning",
    ketenfase_van: "",
    R1: true,
    R2: true,
    R3: false,
    R4: false,
    R5: false,
    R6: false,
    valt_deze_mogelijkheid_onder_een_overheidsopdracht_of_consessie_opdracht: false,
    soort_opdracht: "",
    waar_valt_het_onder: "",
    kop_6_ministappenplan: "Start met duurzaamheidseisen in tenders",
    ministappenplan:
      "1. Schrijf een tender uit waarin duurzaamheidseisen worden meegewogen\n\n2. Pak ter inspiratie de Roadmap Circulaire Gronduitgifte erbij\n\n3. Beoordeel de inschrijvingen",
    links_ministappenplan:
      "https://www.pianoo.nl/nl/document/14280/roadmap-circulaire-gronduitgifte",
    goed_in_combinatie_met_maatregel_vul_in_titel_voor_meer_mogelijkheden_vul_in_met_komma:
      "",
    rechtsgebied: "Privaatrecht",
    subrechtsgebied: "Erfpacht",
    citeertitel: "Burgelijk Wetboek Boek 5",
    geldend_vanaf: "01/01/1992",
    type_document: "Wet in formele zin",
    waardeketen: {
      transitieagenda: "Gebouwde Omgeving",
    },
    casus: "Houtbouw",
  },
  {
    id: "8",
    artikel: "2.31a",
    circulair: true,
    titel: "Duurzaam aanbesteden via innovatiepartnerschap",
    kop_1_samenvatting_juridische_maatregel:
      "Wat is een innovatiepartnerschap?",
    introductie_juridische_maatregel:
      "Als aanbestedende diensten een opdracht uitschrijven, kunnen ze daarvoor verschillende aanbestedingsprocedures gebruiken. Een ervan is innovatiepartnerschap. In deze procedure gaan aanbestedende diensten en aanbieder(s) een relatief lange samenwerking met elkaar aan. Aanbesteders kiezen meestal voor innovatiepartnerschap als de opdracht gericht is op de ontwikkeling van een innovatief product of innovatieve dienst die nog niet op de markt is. Het verschil met andere procedures is dat na de ontwikkelfase niet opnieuw een (open) aanbestedingsprocedure hoeft plaats te vinden. In plaats daarvan kunnen de partijen meteen samen tot de commerciële fase overgaan. De aanbesteder kan de aanbieder – na een succesvol ontwikkeltraject – dus gegarandeerde afname en een langdurige samenwerking bieden. Met die zekerheid dat ze het project zelf mogen uitrollen, zijn inschrijvers bereid meer in de oplossing te investeren. Het resultaat: grotere kans op succesvolle grootschalige innovatie.   ",
    kop_2_toepassing_juridische_maatregel: "",
    toepassing_juridische_maatregel: "",
    is_er_een_praktijk_voorbeeld: true,
    kop_3_uit_de_praktijk:
      "[KADER] Innovatiepartnerschap in de praktijk (1): Hof van Twente",
    uit_de_praktijk:
      "Toen gemeente Hof van Twente in de dorpen Markelo en Delden twee nieuwe, duurzame kindcentra wilde laten bouwen, kozen ze voor innovatiepartnerschap. Een mijlpaal: het was de eerste keer dat een onderwijsbouwproject via deze procedure tot stand kwam. De onderzoeks- en ontwikkelfase werden direct gekoppeld aan de realisatie van de gebouwen, die klimaatneutraal, simpel van opzet en slim ontworpen moesten zijn. Na een grondige onderzoeksfase, koos de gemeente voor een consortium van een vastgoedontwikkelaar, architectenbureau en een installatiebureau. In februari 2019 begon men met de bouw. In het voorjaar van 2020 openden de deuren van het eerste gebouw, een jaar later stond het tweede kindcentra er. De gebouwen staan bovenaan de lijst van meest duurzame schoolgebouwen van Europa.\n\n[KADER] Innovatiepartnerschap in de praktijk (2): Amsterdam\nAmsterdam volgt het voorbeeld van Hof van Twente. De komende jaren wil de gemeente meerdere nieuwe, duurzame en kwalitatief hoogwaardige schoolgebouwen realiseren, onder meer in de IJburgse wijk Strandeiland. Als aanbestedingsprocedure kiest de gemeente voor innovatiepartnerschap. De aanbestedingsfase om het meest geschikte consortium te vinden, is in 2022 begonnen.    \nLees meer over dit voorbeeld van innovatiepartnerschap in Amsterdam",
    voorbeeld_link:
      "https://www.pianoo.nl/sites/default/files/media/documents/Innovatiepartnerschapindepraktijk-januari%202019.pdf\n\nhttps://www.tubantia.nl/hof-van-twente/de-groenste-scholen-van-europa-staan-in-hof-van-twente-duurzaamheid-zit-in-ons-dna~aa9b5a5d/?referrer=https%3A%2F%2Fwww.google.com%2F&cb=f20199f831022acf1702151368787071&auth_rd=1\n\nhttps://www.duurzaamgebouwd.nl/artikel/20211122-innovatiepartnerschap-meer-duurzame-scholen-minder-faalkosten",
    afbeelding_van_voorbeeld_link: "",
    kop_4_eisen_en_beperkingen: "Innovatiepartnerschap: eisen en beperkingen",
    eisen_en_beperkingen:
      "- In de aanbestedingsfase van het innovatiepartnerschap kunnen verschillende aanbieders meedoen. Gaandeweg het traject kunnen zij afhaken of afvallen. Na de ontwikkelfase kunnen er geen nieuwe partijen meer aanhaken;\n- De doorlooptijd van innovatiepartnerschap is lang en intensief. Er vindt vaker overleg plaats tussen verschillende partijen, waarover telkens uitgebreid verslag gedaan moet worden. Dit leidt automatisch tot hogere transactiekosten, die niet altijd proportioneel zijn.\n\n\n",
    kop_5_juridische_toelichting: juridische_toelichting,
    juridische_toelichting:
      "Dit volgt uit art. 2.30 jo. 2.28 lid 1 sub a en b Aanbestedingswet. De stappen die de aanbestedende dienst moet doorlopen, volgen uit art. 2.31 Aanbestedingswet.",
    juridische_houdbaarheid: 3,
    duidelijkheid_wet: "",
    beschikbare_jurisprudentie: "",
    complexiteit_maatregel: "",
    kans_op_schadeclaims: "",
    niet_juridische_beoordeling: "",
    juridische_invloed: 3,
    bereik: "",
    duur: "",
    frequentie: "",
    omvang: "",
    nationaal: true,
    provinciaal: true,
    waterschappen: true,
    gemeentelijk: true,
    type_beleidsinstrument: "Juridisch",
    planningsfase_binnen_de_gebiedsontwikkeling: "Verkenning",
    ketenfase_van: "",
    R1: true,
    R2: false,
    R3: false,
    R4: false,
    R5: false,
    R6: false,
    valt_deze_mogelijkheid_onder_een_overheidsopdracht_of_consessie_opdracht: false,
    soort_opdracht: "",
    waar_valt_het_onder: "",
    kop_6_ministappenplan:
      "Eerste stappen naar aanbesteden via innovatiepartnerschap",
    ministappenplan:
      "1. Bepaal of deze manier van aanbesteden pas bij het voorliggende vraagstuk\n\n2. Stel de mededingingsstukken op\n\n3. Beoordeel de inschrijvingen\n\n4. Onderzoek- en ontwikkelingsfase\n\n5. Aankoop\n",
    links_ministappenplan: "",
    goed_in_combinatie_met_maatregel_vul_in_titel_voor_meer_mogelijkheden_vul_in_met_komma:
      "",
    rechtsgebied: "Privaatrecht",
    subrechtsgebied: "Aanbesteding",
    citeertitel: "Aanbestedingswet 2012",
    geldend_vanaf: "01/04/2013",
    type_document: "Wet in formele zin",
    waardeketen: {
      transitieagenda: "Gebouwde Omgeving",
    },
    casus: "Houtbouw",
  },
];
