name: Backup Routine
on:
  schedule:
    # Runs at 04:00 UTC on the 1st and 17th of every month
    - cron: "0 10 */30 * *"
jobs:
  backup-dataset:
    runs-on: ubuntu-latest
    name: Backup dataset
    steps:
      - uses: actions/checkout@v2
      - run: npx @sanity/cli dataset export production backup.tar.gz
        working-directory: studio
        env: 
          SANITY_STUDIO_API_PROJECT_ID: 2vfoxb3h
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: production
          path: studio/backup.tar.gz
          retention-days: 5
